theme: jekyll-theme-cayman
title: DeepHyper
description: Scale Your Exploration
show_downloads: true
github:
  repository_url: https://github.com/deephyper/deephyper
  zip_url: https://github.com/deephyper/deephyper/zipball/master
  tar_url: https://github.com/deephyper/deephyper/tarball/master
